// @aufbau/webfonts/data.js
// generated by .github/scripts/generate-webfonts.mjs — do not edit by hand.
// edit handpicked.txt instead, then run `npm run generate:webfonts`.
//
// single source of truth for the collection, consumed by the preview page, the
// per-font css generator and the js api. license values come from the google/fonts
// folder and should be spot-checked before publishing.

const fonts = [

// ::: sans ::::::::::::::::::::::::::::::::::::::::::::::

{
  id         : 'inter',
  name       : 'Inter',
  designer   : 'Rasmus Andersson',
  source     : 'https://www.github.com/rsms/inter',
  license    : 'OFL-1.1',
  commercial : true,
  category   : 'sans',
  fallback   : 'sans-serif',
  features   : [],
  faces      : [
    { weight: '100 900', style: 'normal', file: 'files/inter/inter-variable.ttf' },
    { weight: '100 900', style: 'italic', file: 'files/inter/inter-italic-variable.ttf' },
  ],
},

{
  id         : 'manrope',
  name       : 'Manrope',
  designer   : 'Mikhail Sharanda',
  source     : 'https://github.com/aaronbell/manrope',
  license    : 'OFL-1.1',
  commercial : true,
  category   : 'sans',
  fallback   : 'sans-serif',
  features   : [],
  faces      : [
    { weight: '200 800', style: 'normal', file: 'files/manrope/manrope-variable.ttf' },
  ],
},

// ::: serif :::::::::::::::::::::::::::::::::::::::::::::

{
  id         : 'vollkorn',
  name       : 'Vollkorn',
  designer   : 'Friedrich Althausen',
  source     : 'https://github.com/FAlthausen/Vollkorn-Typeface',
  license    : 'OFL-1.1',
  commercial : true,
  category   : 'serif',
  fallback   : 'serif',
  features   : ['liga', 'onum'],
  faces      : [
    { weight: '400 900', style: 'normal', file: 'files/vollkorn/vollkorn-variable.ttf' },
    { weight: '400 900', style: 'italic', file: 'files/vollkorn/vollkorn-italic-variable.ttf' },
  ],
},

// ::: mono ::::::::::::::::::::::::::::::::::::::::::::::

{
  id         : 'jetbrains-mono',
  name       : 'JetBrains Mono',
  designer   : 'JetBrains, Philipp Nurullin, Konstantin Bulenkov',
  source     : 'https://github.com/JetBrains/JetBrainsMono',
  license    : 'OFL-1.1',
  commercial : true,
  category   : 'mono',
  fallback   : 'monospace',
  features   : ['calt'],
  faces      : [
    { weight: '100 800', style: 'normal', file: 'files/jetbrains-mono/jetbrains-mono-variable.ttf' },
    { weight: '100 800', style: 'italic', file: 'files/jetbrains-mono/jetbrains-mono-italic-variable.ttf' },
  ],
},

]; // end: fonts

export         { fonts };
export default { fonts };
