// regenerates ../manifest.js from the pattern modules in ../lib.
// run from the patterns/ dir:  node scripts/manifest.js
//
// the manifest holds only static metadata (id, name, vars) so list() and pickers
// stay cheap; the render implementations live in ./lib/<id>.js and load on demand.

import { readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const libDir = join(here, '..', 'lib');

const files = readdirSync(libDir).filter(f => f.endsWith('.js') && f !== 'index.js').sort();

const entries = [];
for (const file of files) {
  const id = file.replace(/\.js$/, '');
  const mod = await import(join(libDir, file));
  if (!mod.id) { console.error(`skip ${file}: no id export`); continue; }
  if (mod.id !== id) console.error(`warning: ${file} exports id "${mod.id}" (expected "${id}")`);
  entries.push({ id: mod.id, name: mod.name, vars: mod.vars });
}

const body = entries.map(e =>
  `  ${JSON.stringify(e.id)}: { id: ${JSON.stringify(e.id)}, name: ${JSON.stringify(e.name)}, vars: ${JSON.stringify(e.vars)} },`
).join('\n');

const out = `// @aufbau/patterns/manifest.js
// GENERATED by scripts/manifest.js — do not edit by hand.
// static metadata (id, name, vars) for every pattern, so list() and pickers read
// this one file instead of importing all ${entries.length} implementation modules.
// the render implementations stay in ./lib/<id>.js and load on demand.

export const manifest = {
${body}
};

export default manifest;
`;

writeFileSync(join(here, '..', 'manifest.js'), out);
console.log(`wrote patterns/manifest.js with ${entries.length} entries`);
