// regenerates lib/<id>.d.ts for every pattern module, points the module at it
// with a @ts-self-types comment and lists every pattern in deno.json's exports.
// run from the patterns/ dir:  node scripts/types.js

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here   = dirname(fileURLToPath(import.meta.url));
const libDir = join(here, '..', 'lib');
const files  = readdirSync(libDir).filter(file => file.endsWith('.js')).sort();

const TS = { angle: 'number', color: 'string', number: 'number' };

const camel = id => id.replace(/-(\w)/g, (_, char) => char.toUpperCase());

// what a variable takes, its default and its range, for the docs
function describeVar (spec) {
  const range = spec.min != null && spec.max != null ? `, ${spec.min} to ${spec.max}${spec.unit ? ' ' + spec.unit : ''}` : '';
  const live  = spec.bake ? ' Baked into the markup.' : ' Live, a css custom property with `live: true`.';
  return `Default \`${JSON.stringify(spec.default)}\`${range}.${live}`;
}

for (const file of files) {
  const id     = file.replace(/\.js$/, '');
  const path   = join(libDir, file);
  const source = readFileSync(path, 'utf8');
  const m      = await import(path);
  const fn     = camel(id);

  const options = Object.entries(m.vars).map(([key, spec]) => `  /** ${describeVar(spec)} */\n  ${key}?: ${TS[spec.type] ?? 'unknown'};`).join('\n');
  const varKeys = Object.keys(m.vars).map(key => `  /** The \`${key}\` variable. */\n  readonly ${key}: VarSpec;`).join('\n');

  const lines = [
    '// GENERATED by scripts/types.js — do not edit by hand.',
    '',
    '/**',
    ` * ${m.name}: a tileable svg pattern.`,
    ' *',
    ' * @example',
    ' * ```js',
    ` * import ${fn} from '@aufbau/patterns/${id}';`,
    ` * import { apply } from '@aufbau/patterns';`,
    ' *',
    ` * ${fn}({ fg: '#f0f' });          // the <svg> tile`,
    ` * await apply('.box', '${id}', { fg: '#f0f', motion: 'down' });`,
    ' * ```',
    ' *',
    ' * @module',
    ' */',
    '',
    `import type { PatternOptions, VarSpec } from '../types.d.ts';`,
    '',
    `/** The options of ${m.name}. */`,
    'export interface Options extends PatternOptions {',
    options,
    '}',
    '',
    `/** The id: \`${id}\`. */`,
    `export declare const id: '${id}';`,
    '',
    `/** The display name: \`${m.name}\`. */`,
    `export declare const name: '${m.name}';`,
    '',
    '/** The variables, what each takes and its default. */',
    'export declare const vars: {',
    varKeys,
    '};',
    '',
    '/** The whole `<svg>` tile for a set of options. */',
    `export default function ${fn} (options?: Options): string;`,
  ];

  writeFileSync(join(libDir, `${id}.d.ts`), lines.join('\n') + '\n');

  if (!source.includes('@ts-self-types')) {
    const [first, ...rest] = source.split('\n');
    writeFileSync(path, [first, `// @ts-self-types="./${id}.d.ts"`, ...rest].join('\n'));
  }
}

// every pattern is an entry point of the package on jsr
const config  = JSON.parse(readFileSync(join(here, '..', 'deno.json'), 'utf8'));
const exports = {
  '.'        : './index.js',
  './core'   : './core.js',
  './motion' : './motion.js',
  ...Object.fromEntries(files.map(file => [`./${file.replace(/\.js$/, '')}`, `./lib/${file}`])),
};
const { publish, ...head } = config;
writeFileSync(join(here, '..', 'deno.json'), JSON.stringify({ ...head, exports, publish }, null, 2) + '\n');

console.log(`types for ${files.length} patterns`);
