// @aufbau/.github/scripts/generate-assets.mjs
// single source of truth is the js: every filter/pattern is a function. this script
// renders each one in its live (var-driven) form and writes the static artefacts
// under @aufbau/svg — the .svg files plus the data.json5 catalogues — so external,
// build-free consumers keep working without importing the js. run it after editing
// any lib/*.js: `npm run generate` (see the generate-assets workflow for ci).

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath }    from 'node:url';

import { wrapSvg }  from '../../filters/core.js';
import { filters }  from '../../filters/lib/index.js';
import { patterns } from '../../patterns/lib/index.js';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const SVG  = resolve(ROOT, 'svg');

// :::::: FORMATTING :::::::::::::::::::::::::::::::::::::::::::::

// light pretty-printer: one element per line, two-space indent by nesting depth.
// the generated markup has no text nodes, so splitting on element boundaries is safe.
function prettify (svg) {
  const parts = svg.replace(/>\s+</g, '><').replace(/></g, '>\n<').split('\n');
  let depth = 0, out = '';
  for (const raw of parts) {
    const line = raw.trim();
    if (!line) continue;
    if (line.startsWith('</')) depth--;
    out += '  '.repeat(Math.max(depth, 0)) + line + '\n';
    const opens = /^<[^/!?]/.test(line) && !/\/>$/.test(line) && !/<\/[a-z]/i.test(line);
    if (opens) depth++;
  }
  return out.trimEnd() + '\n';
}

// serialises the catalogue as json5: a header comment plus plain json (valid json5).
function toJson5 (path, list) {
  const body = JSON.stringify(list.map(({ id, name, vars }) => ({ id, name, vars })), null, 2);
  return `// ${path}\n// generated by .github/scripts/generate-assets.mjs — do not edit by hand.\n// edit the matching lib/*.js instead, then run \`npm run generate\`.\n\n${body}\n`;
}

// :::::: WRITE :::::::::::::::::::::::::::::::::::::::::::::::::::

async function write (path, content) {
  const full = resolve(SVG, path);
  await mkdir(dirname(full), { recursive: true });
  await writeFile(full, content);
  console.log('  wrote', path);
}

async function generateKind (kind, registry, toSvg) {
  console.log(kind + ':');
  const entries = Object.values(registry);
  // canvas-only filters (render === null) have no svg asset; catalogue still lists them.
  for (const meta of entries) {
    if (meta.render) await write(`${kind}/${meta.id}.svg`, prettify(toSvg(meta)));
  }
  await write(`${kind}/data.json5`, toJson5(`@aufbau/svg/${kind}/data.json5`, entries));
  return entries.map(({ id, name }) => ({ id, name }));
}

const filterList  = await generateKind('filters' , filters , m => wrapSvg(m.render({ live: true })));
const patternList = await generateKind('patterns', patterns, m => m.render({ live: true }));

// combined catalogue consumed by svg/index.html and tooling.
await write('index.json5',
  `// @aufbau/svg/index.json5\n// generated by .github/scripts/generate-assets.mjs — do not edit by hand.\n\n` +
  JSON.stringify({ filters: filterList, patterns: patternList }, null, 2) + '\n');

console.log('done.');
