// @aufbau/.github/scripts/generate-assets.mjs
// single source of truth is the js: every filter/pattern is a function. this script
// renders each one in its live (var-driven) form and writes the static artefacts
// under @aufbau/svg — the .svg files plus the data.json5 catalogues — so external,
// build-free consumers keep working without importing the js. run it after editing
// any lib/*.js: `npm run generate` (see the generate-assets workflow for ci).

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath }    from 'node:url';

import { wrapSvg }             from '../../filters/core.js';
import { filters, backendsOf } from '../../filters/lib/index.js';
import { patterns }            from '../../patterns/lib/index.js';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const SVG  = resolve(ROOT, 'svg');

// :::::: FORMATTING :::::::::::::::::::::::::::::::::::::::::::::

// light pretty-printer: one element per line, two-space indent by nesting depth.
// the generated markup has no text nodes, so splitting on element boundaries is safe.
function prettify (svg) {
  const parts = svg.replace(/>\s+</g, '><').replace(/></g, '>\n<').split('\n');
  let depth = 0, out = '';
  for (const raw of parts) {
    const line = raw.trim();
    if (!line) continue;
    if (line.startsWith('</')) depth--;
    out += '  '.repeat(Math.max(depth, 0)) + line + '\n';
    const opens = /^<[^/!?]/.test(line) && !/\/>$/.test(line) && !/<\/[a-z]/i.test(line);
    if (opens) depth++;
  }
  return out.trimEnd() + '\n';
}

// wraps a pre-built catalogue array as json5: a header comment plus plain json.
function toJson5 (path, entries) {
  return `// ${path}\n// generated by .github/scripts/generate-assets.mjs — do not edit by hand.\n// edit the matching lib/*.js instead, then run \`npm run generate\`.\n\n${JSON.stringify(entries, null, 2)}\n`;
}

// catalogue entry per kind. filters carry their backend capabilities (css/svg/canvas/webgl)
// so tooling and the editor can pick a backend without importing the js; patterns list the
// two application modes they always support.
const filterEntry  = m => ({ id: m.id, name: m.name, vars: m.vars, backends: backendsOf(m) });
const patternEntry = m => ({ id: m.id, name: m.name, vars: m.vars, modes: ['datauri', 'defs'] });

// :::::: WRITE :::::::::::::::::::::::::::::::::::::::::::::::::::

async function write (path, content) {
  const full = resolve(SVG, path);
  await mkdir(dirname(full), { recursive: true });
  await writeFile(full, content);
  console.log('  wrote', path);
}

async function generateKind (kind, registry, toSvg, toEntry) {
  console.log(kind + ':');
  const metas = Object.values(registry);
  // canvas/webgl-only filters (render === null) have no svg asset; catalogue still lists them.
  for (const meta of metas) {
    if (meta.render) await write(`${kind}/${meta.id}.svg`, prettify(toSvg(meta)));
  }
  const entries = metas.map(toEntry);
  await write(`${kind}/data.json5`, toJson5(`@aufbau/svg/${kind}/data.json5`, entries));
  return entries;
}

const filterList  = await generateKind('filters' , filters , m => wrapSvg(m.render({ live: true })), filterEntry);
const patternList = await generateKind('patterns', patterns, m => m.render({ live: true }), patternEntry);

// combined, lightweight index consumed by svg/index.html and tooling — id/name plus each
// filter's backends for a quick capability lookup without the full vars.
await write('index.json5',
  `// @aufbau/svg/index.json5\n// generated by .github/scripts/generate-assets.mjs — do not edit by hand.\n\n` +
  JSON.stringify({
    filters:  filterList.map(({ id, name, backends }) => ({ id, name, backends })),
    patterns: patternList.map(({ id, name }) => ({ id, name })),
  }, null, 2) + '\n');

console.log('done.');
