// regenerates ../manifest.js from the filter modules in ../lib.
// run from the filters/ dir:  node scripts/manifest.js
//
// the manifest holds static metadata (id, name, vars) plus raw backend-presence
// flags (svg/css/canvas/webgl) so list(), supports() and pipeline's webgl-run
// coalescing stay synchronous without importing any implementation. the render/
// css/canvas/webgl implementations live in ./lib/<id>.js and load on demand.

import { readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const libDir = join(here, '..', 'lib');

const files = readdirSync(libDir).filter(f => f.endsWith('.js') && f !== 'index.js').sort();

const entries = [];
for (const file of files) {
  const id  = file.replace(/\.js$/, '');
  const m   = await import(join(libDir, file));
  if (!m.id) { console.error(`skip ${file}: no id export`); continue; }
  if (m.id !== id) console.error(`warning: ${file} exports id "${m.id}" (expected "${id}")`);

  // mirror the full-meta derivation so the flags match what load() builds:
  //   render = svg export, or the default export unless a canvas/webgl backend exists.
  const render = m.svg ?? ((m.canvas || m.webgl) ? null : m.default) ?? null;
  const backends = { svg: !!render, css: !!m.css, canvas: !!m.canvas, webgl: !!m.webgl };
  entries.push({ id: m.id, name: m.name, vars: m.vars, backends });
}

const body = entries.map(e =>
  `  ${JSON.stringify(e.id)}: { id: ${JSON.stringify(e.id)}, name: ${JSON.stringify(e.name)}, ` +
  `vars: ${JSON.stringify(e.vars)}, backends: ${JSON.stringify(e.backends)} },`
).join('\n');

const out = `// @aufbau/filters/manifest.js
// GENERATED by scripts/manifest.js — do not edit by hand.
// static metadata (id, name, vars) and raw backend-presence flags for every filter,
// so list()/supports() read this one file instead of importing all ${entries.length} implementation
// modules. the implementations stay in ./lib/<id>.js and load on demand.

export const manifest = {
${body}
};

export default manifest;
`;

writeFileSync(join(here, '..', 'manifest.js'), out);
console.log(`wrote filters/manifest.js with ${entries.length} entries`);
