// regenerates lib/<id>.d.ts for every filter module and points the module at it
// with a @ts-self-types comment. run from the filters/ dir:  node scripts/types.js
//
// the description is the module's leading comment, the options come from its
// vars, the example from its backend: an svg render, a canvas pass or a shader.

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here   = dirname(fileURLToPath(import.meta.url));
const libDir = join(here, '..', 'lib');
const files  = readdirSync(libDir).filter(file => file.endsWith('.js') && file !== 'registry.js').sort();

const TS = { angle: 'number', boolean: 'boolean', color: 'string', duration: 'string', integer: 'number', number: 'number', text: 'string' };

const camel = id => id.replace(/-(\w)/g, (_, char) => char.toUpperCase());

// the leading // comment after the path line, as one paragraph
function descriptionOf (source) {
  const lines = [];
  for (const line of source.split('\n').slice(1)) {
    if (!line.startsWith('//')) break;
    if (line.includes('@ts-self-types')) continue;
    lines.push(line.replace(/^\/\/\s?/, ''));
  }
  const text = lines.join(' ').replace(/\s+/g, ' ').trim();
  return text ? text[0].toUpperCase() + text.slice(1) : '';
}

// what a variable takes, its default and its range, for the docs
function describeVar (spec) {
  const range = spec.min != null && spec.max != null ? `, ${spec.min} to ${spec.max}${spec.unit ? ' ' + spec.unit : ''}` : spec.unit ? ` (${spec.unit})` : '';
  const baked = spec.bake ? ' Baked into the markup, never a css custom property.' : '';
  if (spec.type === 'boolean') return `\`false\` holds the effect still. Default \`${spec.default}\`.`;
  return `Default \`${JSON.stringify(spec.default)}\`${range}.${baked}`;
}

function exampleOf (kind, id, name, vars) {
  const option = Object.entries(vars).find(([, spec]) => spec.type !== 'boolean');
  const options = option ? `{ ${option[0]}: ${JSON.stringify(option[1].default)} }` : '';
  const fn = camel(id);

  if (kind === 'svg') return [
    '```js',
    `import ${fn} from '@aufbau/filters/${id}';`,
    `import { apply } from '@aufbau/filters';`,
    '',
    `${fn}(${options});          // the <filter> markup`,
    `await apply('#photo', '${id}'${options ? ', ' + options : ''});`,
    '```',
  ];
  if (kind === 'canvas') return [
    '```js',
    `import { filterToCanvas } from '@aufbau/filters/canvas';`,
    '',
    `await filterToCanvas(canvas, '${id}'${options ? ', ' + options : ''});`,
    '```',
  ];
  return [
    '```js',
    `import { filterToWebgl } from '@aufbau/filters/webgl';`,
    '',
    `await filterToWebgl(canvas, '${id}'${options ? ', ' + options : ''});`,
    '```',
  ];
}

for (const file of files) {
  const id     = file.replace(/\.js$/, '');
  const path   = join(libDir, file);
  const source = readFileSync(path, 'utf8');
  const m      = await import(path);

  const kind = m.default === m.canvas && m.canvas ? 'canvas' : m.default ? 'svg' : 'webgl';
  const what = { canvas: 'a pixel pass over a canvas', svg: 'an svg `<filter>`', webgl: 'a webgl shader' }[kind];
  const description = descriptionOf(source) || `${what[0].toUpperCase()}${what.slice(1)}.`;

  const options = Object.entries(m.vars).map(([key, spec]) => [
    `  /** ${describeVar(spec)} */`,
    `  ${key}?: ${TS[spec.type] ?? 'unknown'};`,
  ].join('\n')).join('\n');

  const varKeys = Object.keys(m.vars).map(key => `  /** The \`${key}\` variable. */\n  readonly ${key}: VarSpec;`).join('\n');

  const lines = [
    '// GENERATED by scripts/types.js — do not edit by hand.',
    '',
    '/**',
    ` * ${m.name}: ${description}`,
    ' *',
    ' * @example',
    ...exampleOf(kind, id, m.name, m.vars).map(line => ` * ${line}`.trimEnd()),
    ' *',
    ' * @module',
    ' */',
    '',
    `import type { ${[m.webgl && 'WebglBackend', 'FilterOptions', 'VarSpec'].filter(Boolean).join(', ')} } from '../types.d.ts';`,
    '',
    `/** The options of ${m.name}. */`,
    `export interface Options extends FilterOptions {`,
    options,
    '}',
    '',
    `/** The id: \`${id}\`. */`,
    `export declare const id: '${id}';`,
    '',
    `/** The display name: \`${m.name}\`. */`,
    `export declare const name: '${m.name}';`,
    '',
    `/** The variables, what each takes and its default. */`,
    `export declare const vars: {`,
    varKeys,
    '};',
  ];

  if (kind === 'svg')    lines.push('', '/** The `<filter>` markup for a set of options. */', `export default function ${camel(id)} (options?: Options): string;`);
  if (kind === 'canvas') lines.push('', '/** Filters the pixels of an image in place. */', 'export declare function canvas (image: ImageData, options?: Options): void;', '', 'export default canvas;');
  if (m.css)   lines.push('', '/** The native css filter function for a set of options. */', 'export declare function css (options?: Options): string;');
  if (m.webgl) lines.push('', '/** The shader passes. */', 'export declare const webgl: WebglBackend;');
  if (m.svg)   lines.push('', '/** The `<filter>` markup for a set of options. */', 'export declare function svg (options?: Options): string;');

  // shader sources other filters build on
  for (const key of Object.keys(m).filter(key => /^[A-Z]+$/.test(key))) {
    lines.push('', `/** The ${key.toLowerCase()} shader source, shared with the filters that build on it. */`, `export declare const ${key}: string;`);
  }

  writeFileSync(join(libDir, `${id}.d.ts`), lines.join('\n') + '\n');

  // the module points at its types, right below its path line
  if (!source.includes('@ts-self-types')) {
    const [first, ...rest] = source.split('\n');
    writeFileSync(path, [first, `// @ts-self-types="./${id}.d.ts"`, ...rest].join('\n'));
  }
}

console.log(`types for ${files.length} filters`);

// every filter is an entry point of the package on jsr
const config = JSON.parse(readFileSync(join(here, '..', 'deno.json'), 'utf8'));
const exports = {
  '.'          : './index.js',
  './canvas'   : './canvas.js',
  './core'     : './core.js',
  './pipeline' : './pipeline.js',
  './webgl'    : './webgl.js',
  ...Object.fromEntries(files.map(file => [`./${file.replace(/\.js$/, '')}`, `./lib/${file}`])),
};
const { publish, ...head } = config;
writeFileSync(join(here, '..', 'deno.json'), JSON.stringify({ ...head, exports, publish }, null, 2) + '\n');
