// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Crosses: a tileable svg pattern.
 *
 * @example
 * ```js
 * import crosses from '@aufbau/patterns/crosses';
 * import { apply } from '@aufbau/patterns';
 *
 * crosses({ fg: '#f0f' });          // the <svg> tile
 * await apply('.box', 'crosses', { fg: '#f0f', motion: 'down' });
 * ```
 *
 * @module
 */

import type { PatternOptions, VarSpec } from '../types.d.ts';

/** The options of Crosses. */
export interface Options extends PatternOptions {
  /** Default `"transparent"`. Live, a css custom property with `live: true`. */
  bg?: string;
  /** Default `"#000000"`. Live, a css custom property with `live: true`. */
  fg?: string;
  /** Default `0`, 0 to 360 deg. Baked into the markup. */
  rotate?: number;
  /** Default `24`, 6 to 100. Baked into the markup. */
  size?: number;
  /** Default `4`, 1 to 20 px. Baked into the markup. */
  thickness?: number;
}

/** The id: `crosses`. */
export declare const id: 'crosses';

/** The display name: `Crosses`. */
export declare const name: 'Crosses';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `bg` variable. */
  readonly bg: VarSpec;
  /** The `fg` variable. */
  readonly fg: VarSpec;
  /** The `rotate` variable. */
  readonly rotate: VarSpec;
  /** The `size` variable. */
  readonly size: VarSpec;
  /** The `thickness` variable. */
  readonly thickness: VarSpec;
};

/** The whole `<svg>` tile for a set of options. */
export default function crosses (options?: Options): string;
