// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Dots: a tileable svg pattern.
 *
 * @example
 * ```js
 * import dots from '@aufbau/patterns/dots';
 * import { apply } from '@aufbau/patterns';
 *
 * dots({ fg: '#f0f' });          // the <svg> tile
 * await apply('.box', 'dots', { fg: '#f0f', motion: 'down' });
 * ```
 *
 * @module
 */

import type { PatternOptions, VarSpec } from '../types.d.ts';

/** The options of Dots. */
export interface Options extends PatternOptions {
  /** Default `"transparent"`. Live, a css custom property with `live: true`. */
  bg?: string;
  /** Default `"#000000"`. Live, a css custom property with `live: true`. */
  fg?: string;
  /** Default `3`, 0 to 10. Baked into the markup. */
  radius?: number;
  /** Default `0`, 0 to 360 deg. Baked into the markup. */
  rotate?: number;
  /** Default `20`, 4 to 100. Baked into the markup. */
  size?: number;
}

/** The id: `dots`. */
export declare const id: 'dots';

/** The display name: `Dots`. */
export declare const name: 'Dots';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `bg` variable. */
  readonly bg: VarSpec;
  /** The `fg` variable. */
  readonly fg: VarSpec;
  /** The `radius` variable. */
  readonly radius: VarSpec;
  /** The `rotate` variable. */
  readonly rotate: VarSpec;
  /** The `size` variable. */
  readonly size: VarSpec;
};

/** The whole `<svg>` tile for a set of options. */
export default function dots (options?: Options): string;
