// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Rings: a tileable svg pattern.
 *
 * @example
 * ```js
 * import rings from '@aufbau/patterns/rings';
 * import { apply } from '@aufbau/patterns';
 *
 * rings({ fg: '#f0f' });          // the <svg> tile
 * await apply('.box', 'rings', { fg: '#f0f', motion: 'down' });
 * ```
 *
 * @module
 */

import type { PatternOptions, VarSpec } from '../types.d.ts';

/** The options of Rings. */
export interface Options extends PatternOptions {
  /** Default `"transparent"`. Live, a css custom property with `live: true`. */
  bg?: string;
  /** Default `"#000000"`. Live, a css custom property with `live: true`. */
  fg?: string;
  /** Default `0`, 0 to 360 deg. Baked into the markup. */
  rotate?: number;
  /** Default `24`, 6 to 100. Baked into the markup. */
  size?: number;
  /** Default `2`, 0.5 to 12 px. Baked into the markup. */
  width?: number;
}

/** The id: `rings`. */
export declare const id: 'rings';

/** The display name: `Rings`. */
export declare const name: 'Rings';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `bg` variable. */
  readonly bg: VarSpec;
  /** The `fg` variable. */
  readonly fg: VarSpec;
  /** The `rotate` variable. */
  readonly rotate: VarSpec;
  /** The `size` variable. */
  readonly size: VarSpec;
  /** The `width` variable. */
  readonly width: VarSpec;
};

/** The whole `<svg>` tile for a set of options. */
export default function rings (options?: Options): string;
