// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Bad TV: An svg `<filter>`.
 *
 * @example
 * ```js
 * import badTv from '@aufbau/filters/bad-tv';
 * import { apply } from '@aufbau/filters';
 *
 * badTv({ distortion: 8 });          // the <filter> markup
 * await apply('#photo', 'bad-tv', { distortion: 8 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Bad TV. */
export interface Options extends FilterOptions {
  /** `false` holds the effect still. Default `true`. */
  animate?: boolean;
  /** Default `8`, 0 to 40. */
  distortion?: number;
  /** Default `"2s"`. Baked into the markup, never a css custom property. */
  speed?: string;
}

/** The id: `bad-tv`. */
export declare const id: 'bad-tv';

/** The display name: `Bad TV`. */
export declare const name: 'Bad TV';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `animate` variable. */
  readonly animate: VarSpec;
  /** The `distortion` variable. */
  readonly distortion: VarSpec;
  /** The `speed` variable. */
  readonly speed: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function badTv (options?: Options): string;
