// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Barrel Blur: An svg `<filter>`.
 *
 * @example
 * ```js
 * import barrelBlur from '@aufbau/filters/barrel-blur';
 * import { apply } from '@aufbau/filters';
 *
 * barrelBlur({ amount: 8 });          // the <filter> markup
 * await apply('#photo', 'barrel-blur', { amount: 8 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Barrel Blur. */
export interface Options extends FilterOptions {
  /** Default `8`, 0 to 20 px. */
  amount?: number;
  /** Default `0.4`, 0 to 1. Baked into the markup, never a css custom property. */
  size?: number;
}

/** The id: `barrel-blur`. */
export declare const id: 'barrel-blur';

/** The display name: `Barrel Blur`. */
export declare const name: 'Barrel Blur';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `amount` variable. */
  readonly amount: VarSpec;
  /** The `size` variable. */
  readonly size: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function barrelBlur (options?: Options): string;
