// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Bloom: Webgl, multi-pass: threshold the bright areas, blur them (separable h+v), then add the glow back over the original. the classic four-pass bloom, and the showcase for the multi-pass runner (the combine pass reads uSource0 = the untouched original).
 *
 * @example
 * ```js
 * import { filterToWebgl } from '@aufbau/filters/webgl';
 *
 * await filterToWebgl(canvas, 'bloom', { threshold: 0.6 });
 * ```
 *
 * @module
 */

import type { WebglBackend, FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Bloom. */
export interface Options extends FilterOptions {
  /** Default `0.6`, 0 to 1. */
  threshold?: number;
  /** Default `6`, 0 to 20. */
  radius?: number;
  /** Default `1`, 0 to 3. */
  strength?: number;
}

/** The id: `bloom`. */
export declare const id: 'bloom';

/** The display name: `Bloom`. */
export declare const name: 'Bloom';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `threshold` variable. */
  readonly threshold: VarSpec;
  /** The `radius` variable. */
  readonly radius: VarSpec;
  /** The `strength` variable. */
  readonly strength: VarSpec;
};

/** The shader passes. */
export declare const webgl: WebglBackend;
