// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Blur: An svg `<filter>`.
 *
 * @example
 * ```js
 * import blur from '@aufbau/filters/blur';
 * import { apply } from '@aufbau/filters';
 *
 * blur({ amount: 2 });          // the <filter> markup
 * await apply('#photo', 'blur', { amount: 2 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Blur. */
export interface Options extends FilterOptions {
  /** Default `2`, 0 to 20 px. */
  amount?: number;
}

/** The id: `blur`. */
export declare const id: 'blur';

/** The display name: `Blur`. */
export declare const name: 'Blur';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `amount` variable. */
  readonly amount: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function blur (options?: Options): string;

/** The native css filter function for a set of options. */
export declare function css (options?: Options): string;
