// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Brightness: An svg `<filter>`.
 *
 * @example
 * ```js
 * import brightness from '@aufbau/filters/brightness';
 * import { apply } from '@aufbau/filters';
 *
 * brightness({ amount: 1 });          // the <filter> markup
 * await apply('#photo', 'brightness', { amount: 1 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Brightness. */
export interface Options extends FilterOptions {
  /** Default `1`, 0 to 3. */
  amount?: number;
}

/** The id: `brightness`. */
export declare const id: 'brightness';

/** The display name: `Brightness`. */
export declare const name: 'Brightness';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `amount` variable. */
  readonly amount: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function brightness (options?: Options): string;

/** The native css filter function for a set of options. */
export declare function css (options?: Options): string;
