// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Chromatic: Webgl, single-pass: chromatic aberration — the red and blue channels are sampled with an opposite offset along `angle`. the realtime gpu port of the rgb-shift / glitch look, cheap enough to run per video frame.
 *
 * @example
 * ```js
 * import { filterToWebgl } from '@aufbau/filters/webgl';
 *
 * await filterToWebgl(canvas, 'chromatic', { amount: 6 });
 * ```
 *
 * @module
 */

import type { WebglBackend, FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Chromatic. */
export interface Options extends FilterOptions {
  /** Default `6`, 0 to 40 px. */
  amount?: number;
  /** Default `0`, 0 to 360 deg. */
  angle?: number;
}

/** The id: `chromatic`. */
export declare const id: 'chromatic';

/** The display name: `Chromatic`. */
export declare const name: 'Chromatic';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `amount` variable. */
  readonly amount: VarSpec;
  /** The `angle` variable. */
  readonly angle: VarSpec;
};

/** The shader passes. */
export declare const webgl: WebglBackend;
