// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Contrast: An svg `<filter>`.
 *
 * @example
 * ```js
 * import contrast from '@aufbau/filters/contrast';
 * import { apply } from '@aufbau/filters';
 *
 * contrast({ amount: 1 });          // the <filter> markup
 * await apply('#photo', 'contrast', { amount: 1 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Contrast. */
export interface Options extends FilterOptions {
  /** Default `1`, 0 to 3. */
  amount?: number;
}

/** The id: `contrast`. */
export declare const id: 'contrast';

/** The display name: `Contrast`. */
export declare const name: 'Contrast';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `amount` variable. */
  readonly amount: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function contrast (options?: Options): string;

/** The native css filter function for a set of options. */
export declare function css (options?: Options): string;
