// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Displace: Webgl-only: turbulence displacement — warps the image by fbm noise. the realtime gpu port of the svg `wave`/`wobble` displacement (feTurbulence has no glsl equivalent, so this carries its own fbm from noise.js). drive uTime in a rAF loop for a living warp.
 *
 * @example
 * ```js
 * import { filterToWebgl } from '@aufbau/filters/webgl';
 *
 * await filterToWebgl(canvas, 'displace', { amount: 20 });
 * ```
 *
 * @module
 */

import type { WebglBackend, FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Displace. */
export interface Options extends FilterOptions {
  /** Default `20`, 0 to 100 px. */
  amount?: number;
  /** Default `3`, 0.5 to 12. */
  scale?: number;
  /** Default `0.3`, 0 to 2. */
  speed?: number;
}

/** The id: `displace`. */
export declare const id: 'displace';

/** The display name: `Displace`. */
export declare const name: 'Displace';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `amount` variable. */
  readonly amount: VarSpec;
  /** The `scale` variable. */
  readonly scale: VarSpec;
  /** The `speed` variable. */
  readonly speed: VarSpec;
};

/** The shader passes. */
export declare const webgl: WebglBackend;
