// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Dither: Canvas-only: ordered (Bayer 4×4) dithering of the luminance to `levels` tones. the classic newsprint / 1-bit look; not expressible with svg filter primitives.
 *
 * @example
 * ```js
 * import { filterToCanvas } from '@aufbau/filters/canvas';
 *
 * await filterToCanvas(canvas, 'dither', { levels: 2 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Dither. */
export interface Options extends FilterOptions {
  /** Default `2`, 2 to 6. */
  levels?: number;
}

/** The id: `dither`. */
export declare const id: 'dither';

/** The display name: `Dither`. */
export declare const name: 'Dither';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `levels` variable. */
  readonly levels: VarSpec;
};

/** Filters the pixels of an image in place. */
export declare function canvas (image: ImageData, options?: Options): void;

export default canvas;
