// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Dot Screen: Canvas-only: a true half-tone screen — each cell becomes one black dot whose radius grows with the cell's darkness. this is the tone-varying version svg cannot do (the svg `halftone`/`dot-matrix` filters are fixed-grid approximations).
 *
 * @example
 * ```js
 * import { filterToCanvas } from '@aufbau/filters/canvas';
 *
 * await filterToCanvas(canvas, 'dot-screen', { size: 8 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Dot Screen. */
export interface Options extends FilterOptions {
  /** Default `8`, 3 to 32 px. */
  size?: number;
}

/** The id: `dot-screen`. */
export declare const id: 'dot-screen';

/** The display name: `Dot Screen`. */
export declare const name: 'Dot Screen';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `size` variable. */
  readonly size: VarSpec;
};

/** Filters the pixels of an image in place. */
export declare function canvas (image: ImageData, options?: Options): void;

export default canvas;
