// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Dot Matrix: An svg `<filter>`.
 *
 * @example
 * ```js
 * import dotMatrix from '@aufbau/filters/dot-matrix';
 * import { apply } from '@aufbau/filters';
 *
 * dotMatrix({ size: 6 });          // the <filter> markup
 * await apply('#photo', 'dot-matrix', { size: 6 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Dot Matrix. */
export interface Options extends FilterOptions {
  /** Default `6`, 3 to 24. Baked into the markup, never a css custom property. */
  size?: number;
}

/** The id: `dot-matrix`. */
export declare const id: 'dot-matrix';

/** The display name: `Dot Matrix`. */
export declare const name: 'Dot Matrix';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `size` variable. */
  readonly size: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function dotMatrix (options?: Options): string;
