// GENERATED by scripts/types.js — do not edit by hand.

/**
 * DuoTone: An svg `<filter>`.
 *
 * @example
 * ```js
 * import duotone from '@aufbau/filters/duotone';
 * import { apply } from '@aufbau/filters';
 *
 * duotone({ shadow: "#1a1a2e" });          // the <filter> markup
 * await apply('#photo', 'duotone', { shadow: "#1a1a2e" });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of DuoTone. */
export interface Options extends FilterOptions {
  /** Default `"#1a1a2e"`. Baked into the markup, never a css custom property. */
  shadow?: string;
  /** Default `"#e94560"`. Baked into the markup, never a css custom property. */
  highlight?: string;
}

/** The id: `duotone`. */
export declare const id: 'duotone';

/** The display name: `DuoTone`. */
export declare const name: 'DuoTone';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `shadow` variable. */
  readonly shadow: VarSpec;
  /** The `highlight` variable. */
  readonly highlight: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function duotone (options?: Options): string;
