// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Edges: An svg `<filter>`.
 *
 * @example
 * ```js
 * import edges from '@aufbau/filters/edges';
 * import { apply } from '@aufbau/filters';
 *
 * edges({ strength: 1 });          // the <filter> markup
 * await apply('#photo', 'edges', { strength: 1 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Edges. */
export interface Options extends FilterOptions {
  /** Default `1`, 0.2 to 3. Baked into the markup, never a css custom property. */
  strength?: number;
}

/** The id: `edges`. */
export declare const id: 'edges';

/** The display name: `Edges`. */
export declare const name: 'Edges';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `strength` variable. */
  readonly strength: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function edges (options?: Options): string;
