// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Emboss: An svg `<filter>`.
 *
 * @example
 * ```js
 * import emboss from '@aufbau/filters/emboss';
 * import { apply } from '@aufbau/filters';
 *
 * emboss({ strength: 1 });          // the <filter> markup
 * await apply('#photo', 'emboss', { strength: 1 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Emboss. */
export interface Options extends FilterOptions {
  /** Default `1`, 0.2 to 3. Baked into the markup, never a css custom property. */
  strength?: number;
}

/** The id: `emboss`. */
export declare const id: 'emboss';

/** The display name: `Emboss`. */
export declare const name: 'Emboss';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `strength` variable. */
  readonly strength: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function emboss (options?: Options): string;
