// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Fisheye: Webgl-only: real lens distortion. positive amount bulges (fisheye), negative pinches (pincushion). not expressible with svg filter primitives.
 *
 * @example
 * ```js
 * import { filterToWebgl } from '@aufbau/filters/webgl';
 *
 * await filterToWebgl(canvas, 'fisheye', { amount: 1 });
 * ```
 *
 * @module
 */

import type { WebglBackend, FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Fisheye. */
export interface Options extends FilterOptions {
  /** Default `1`, -2 to 2. */
  amount?: number;
}

/** The id: `fisheye`. */
export declare const id: 'fisheye';

/** The display name: `Fisheye`. */
export declare const name: 'Fisheye';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `amount` variable. */
  readonly amount: VarSpec;
};

/** The shader passes. */
export declare const webgl: WebglBackend;
