// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Gaussian Blur: Webgl, multi-pass: a real separable gaussian blur — one horizontal then one vertical pass (9 taps each, linear-sampled weights). the canonical multi-pass example; unlike the css/svg `blur` this is the gpu path for the editor and realtime video.
 *
 * @example
 * ```js
 * import { filterToWebgl } from '@aufbau/filters/webgl';
 *
 * await filterToWebgl(canvas, 'gaussian-blur', { amount: 4 });
 * ```
 *
 * @module
 */

import type { WebglBackend, FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Gaussian Blur. */
export interface Options extends FilterOptions {
  /** Default `4`, 0 to 20 px. */
  amount?: number;
}

/** The id: `gaussian-blur`. */
export declare const id: 'gaussian-blur';

/** The display name: `Gaussian Blur`. */
export declare const name: 'Gaussian Blur';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `amount` variable. */
  readonly amount: VarSpec;
};

/** The shader passes. */
export declare const webgl: WebglBackend;

/** The blur shader source, shared with the filters that build on it. */
export declare const BLUR: string;
