// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Heavy Cyber Glitch: An svg `<filter>`.
 *
 * @example
 * ```js
 * import glitchHeavyCyber from '@aufbau/filters/glitch-heavy-cyber';
 * import { apply } from '@aufbau/filters';
 *
 * glitchHeavyCyber({ frequency: "0.0 0.95" });          // the <filter> markup
 * await apply('#photo', 'glitch-heavy-cyber', { frequency: "0.0 0.95" });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Heavy Cyber Glitch. */
export interface Options extends FilterOptions {
  /** `false` holds the effect still. Default `true`. */
  animate?: boolean;
  /** Default `"0.0 0.95"`. Baked into the markup, never a css custom property. */
  frequency?: string;
  /** Default `40`, 0 to 120. Baked into the markup, never a css custom property. */
  scale?: number;
  /** Default `"1.5s"`. Baked into the markup, never a css custom property. */
  speed?: string;
}

/** The id: `glitch-heavy-cyber`. */
export declare const id: 'glitch-heavy-cyber';

/** The display name: `Heavy Cyber Glitch`. */
export declare const name: 'Heavy Cyber Glitch';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `animate` variable. */
  readonly animate: VarSpec;
  /** The `frequency` variable. */
  readonly frequency: VarSpec;
  /** The `scale` variable. */
  readonly scale: VarSpec;
  /** The `speed` variable. */
  readonly speed: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function glitchHeavyCyber (options?: Options): string;
