// GENERATED by scripts/types.js — do not edit by hand.

/**
 * RGB Glitch: An svg `<filter>`.
 *
 * @example
 * ```js
 * import glitchRgb from '@aufbau/filters/glitch-rgb';
 * import { apply } from '@aufbau/filters';
 *
 * glitchRgb({ offsetX: 3 });          // the <filter> markup
 * await apply('#photo', 'glitch-rgb', { offsetX: 3 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of RGB Glitch. */
export interface Options extends FilterOptions {
  /** Default `3`, -20 to 20. Baked into the markup, never a css custom property. */
  offsetX?: number;
  /** Default `0`, -20 to 20. Baked into the markup, never a css custom property. */
  offsetY?: number;
}

/** The id: `glitch-rgb`. */
export declare const id: 'glitch-rgb';

/** The display name: `RGB Glitch`. */
export declare const name: 'RGB Glitch';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `offsetX` variable. */
  readonly offsetX: VarSpec;
  /** The `offsetY` variable. */
  readonly offsetY: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function glitchRgb (options?: Options): string;
