// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Live Glitch: An svg `<filter>`.
 *
 * @example
 * ```js
 * import glitchLive from '@aufbau/filters/glitch-live';
 * import { apply } from '@aufbau/filters';
 *
 * glitchLive({ speed: "2s" });          // the <filter> markup
 * await apply('#photo', 'glitch-live', { speed: "2s" });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Live Glitch. */
export interface Options extends FilterOptions {
  /** `false` holds the effect still. Default `true`. */
  animate?: boolean;
  /** Default `"2s"`. Baked into the markup, never a css custom property. */
  speed?: string;
}

/** The id: `glitch-live`. */
export declare const id: 'glitch-live';

/** The display name: `Live Glitch`. */
export declare const name: 'Live Glitch';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `animate` variable. */
  readonly animate: VarSpec;
  /** The `speed` variable. */
  readonly speed: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function glitchLive (options?: Options): string;
