// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Glitch: Webgl-only: realtime glitch — horizontal blocks jump sideways and the channels split, all driven by a hash of the row and time. the gpu port of the svg glitch/bad-tv family, cheap enough for video. drive uTime in a rAF loop for the flickering motion.
 *
 * @example
 * ```js
 * import { filterToWebgl } from '@aufbau/filters/webgl';
 *
 * await filterToWebgl(canvas, 'glitch', { intensity: 0.5 });
 * ```
 *
 * @module
 */

import type { WebglBackend, FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Glitch. */
export interface Options extends FilterOptions {
  /** Default `0.5`, 0 to 1. */
  intensity?: number;
  /** Default `1`, 0 to 4. */
  speed?: number;
  /** Default `40`, 5 to 120. */
  blocks?: number;
}

/** The id: `glitch`. */
export declare const id: 'glitch';

/** The display name: `Glitch`. */
export declare const name: 'Glitch';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `intensity` variable. */
  readonly intensity: VarSpec;
  /** The `speed` variable. */
  readonly speed: VarSpec;
  /** The `blocks` variable. */
  readonly blocks: VarSpec;
};

/** The shader passes. */
export declare const webgl: WebglBackend;
