// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Glow: An svg `<filter>`.
 *
 * @example
 * ```js
 * import glow from '@aufbau/filters/glow';
 * import { apply } from '@aufbau/filters';
 *
 * glow({ amount: 4 });          // the <filter> markup
 * await apply('#photo', 'glow', { amount: 4 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Glow. */
export interface Options extends FilterOptions {
  /** Default `4`, 0 to 20 px. */
  amount?: number;
  /** Default `1.4`, 0 to 4. Baked into the markup, never a css custom property. */
  strength?: number;
}

/** The id: `glow`. */
export declare const id: 'glow';

/** The display name: `Glow`. */
export declare const name: 'Glow';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `amount` variable. */
  readonly amount: VarSpec;
  /** The `strength` variable. */
  readonly strength: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function glow (options?: Options): string;
