// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Grain: An svg `<filter>`.
 *
 * @example
 * ```js
 * import grain from '@aufbau/filters/grain';
 * import { apply } from '@aufbau/filters';
 *
 * grain({ frequency: 0.8 });          // the <filter> markup
 * await apply('#photo', 'grain', { frequency: 0.8 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Grain. */
export interface Options extends FilterOptions {
  /** Default `0.8`, 0 to 2. */
  frequency?: number;
  /** Default `2`, 1 to 5. */
  octaves?: number;
  /** Default `0.15`, 0 to 1. */
  opacity?: number;
}

/** The id: `grain`. */
export declare const id: 'grain';

/** The display name: `Grain`. */
export declare const name: 'Grain';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `frequency` variable. */
  readonly frequency: VarSpec;
  /** The `octaves` variable. */
  readonly octaves: VarSpec;
  /** The `opacity` variable. */
  readonly opacity: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function grain (options?: Options): string;
