// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Grayscale: An svg `<filter>`.
 *
 * @example
 * ```js
 * import grayscale from '@aufbau/filters/grayscale';
 * import { apply } from '@aufbau/filters';
 *
 * grayscale({ amount: 1 });          // the <filter> markup
 * await apply('#photo', 'grayscale', { amount: 1 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Grayscale. */
export interface Options extends FilterOptions {
  /** Default `1`, 0 to 1. */
  amount?: number;
}

/** The id: `grayscale`. */
export declare const id: 'grayscale';

/** The display name: `Grayscale`. */
export declare const name: 'Grayscale';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `amount` variable. */
  readonly amount: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function grayscale (options?: Options): string;

/** The native css filter function for a set of options. */
export declare function css (options?: Options): string;
