// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Half Tone: An svg `<filter>`.
 *
 * @example
 * ```js
 * import halftone from '@aufbau/filters/halftone';
 * import { apply } from '@aufbau/filters';
 *
 * halftone({ size: 5 });          // the <filter> markup
 * await apply('#photo', 'halftone', { size: 5 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Half Tone. */
export interface Options extends FilterOptions {
  /** Default `5`, 3 to 20. Baked into the markup, never a css custom property. */
  size?: number;
}

/** The id: `halftone`. */
export declare const id: 'halftone';

/** The display name: `Half Tone`. */
export declare const name: 'Half Tone';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `size` variable. */
  readonly size: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function halftone (options?: Options): string;
