// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Hue & Saturation: An svg `<filter>`.
 *
 * @example
 * ```js
 * import hueSaturation from '@aufbau/filters/hue-saturation';
 * import { apply } from '@aufbau/filters';
 *
 * hueSaturation({ hue: 0 });          // the <filter> markup
 * await apply('#photo', 'hue-saturation', { hue: 0 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Hue & Saturation. */
export interface Options extends FilterOptions {
  /** Default `0`, 0 to 360 deg. */
  hue?: number;
  /** Default `1`, 0 to 3. */
  saturation?: number;
}

/** The id: `hue-saturation`. */
export declare const id: 'hue-saturation';

/** The display name: `Hue & Saturation`. */
export declare const name: 'Hue & Saturation';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `hue` variable. */
  readonly hue: VarSpec;
  /** The `saturation` variable. */
  readonly saturation: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function hueSaturation (options?: Options): string;

/** The native css filter function for a set of options. */
export declare function css (options?: Options): string;
