// GENERATED by scripts/types.js — do not edit by hand.

/**
 * InstaColor: An svg `<filter>`.
 *
 * @example
 * ```js
 * import instacolor from '@aufbau/filters/instacolor';
 * import { apply } from '@aufbau/filters';
 *
 * instacolor({ warmth: 0.08 });          // the <filter> markup
 * await apply('#photo', 'instacolor', { warmth: 0.08 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of InstaColor. */
export interface Options extends FilterOptions {
  /** Default `0.08`, 0 to 0.3. Baked into the markup, never a css custom property. */
  warmth?: number;
  /** Default `1.15`, 0.5 to 2. Baked into the markup, never a css custom property. */
  contrast?: number;
}

/** The id: `instacolor`. */
export declare const id: 'instacolor';

/** The display name: `InstaColor`. */
export declare const name: 'InstaColor';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `warmth` variable. */
  readonly warmth: VarSpec;
  /** The `contrast` variable. */
  readonly contrast: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function instacolor (options?: Options): string;
