// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Invert: An svg `<filter>`.
 *
 * @example
 * ```js
 * import invert from '@aufbau/filters/invert';
 * import { apply } from '@aufbau/filters';
 *
 * invert({ amount: 1 });          // the <filter> markup
 * await apply('#photo', 'invert', { amount: 1 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Invert. */
export interface Options extends FilterOptions {
  /** Default `1`, 0 to 1. */
  amount?: number;
}

/** The id: `invert`. */
export declare const id: 'invert';

/** The display name: `Invert`. */
export declare const name: 'Invert';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `amount` variable. */
  readonly amount: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function invert (options?: Options): string;

/** The native css filter function for a set of options. */
export declare function css (options?: Options): string;
