// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Jitter: An svg `<filter>`.
 *
 * @example
 * ```js
 * import jitter from '@aufbau/filters/jitter';
 * import { apply } from '@aufbau/filters';
 *
 * jitter({ amount: 5 });          // the <filter> markup
 * await apply('#photo', 'jitter', { amount: 5 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Jitter. */
export interface Options extends FilterOptions {
  /** `false` holds the effect still. Default `true`. */
  animate?: boolean;
  /** Default `5`, 0 to 40. */
  amount?: number;
  /** Default `0.5`, 0.05 to 2. */
  frequency?: number;
  /** Default `"0.6s"`. Baked into the markup, never a css custom property. */
  speed?: string;
}

/** The id: `jitter`. */
export declare const id: 'jitter';

/** The display name: `Jitter`. */
export declare const name: 'Jitter';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `animate` variable. */
  readonly animate: VarSpec;
  /** The `amount` variable. */
  readonly amount: VarSpec;
  /** The `frequency` variable. */
  readonly frequency: VarSpec;
  /** The `speed` variable. */
  readonly speed: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function jitter (options?: Options): string;
