// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Kaleidoscope: Webgl-only: folds the image into `segments` mirrored wedges around the centre.
 *
 * @example
 * ```js
 * import { filterToWebgl } from '@aufbau/filters/webgl';
 *
 * await filterToWebgl(canvas, 'kaleidoscope', { segments: 6 });
 * ```
 *
 * @module
 */

import type { WebglBackend, FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Kaleidoscope. */
export interface Options extends FilterOptions {
  /** Default `6`, 2 to 24. */
  segments?: number;
  /** Default `0`, 0 to 360 deg. */
  angle?: number;
}

/** The id: `kaleidoscope`. */
export declare const id: 'kaleidoscope';

/** The display name: `Kaleidoscope`. */
export declare const name: 'Kaleidoscope';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `segments` variable. */
  readonly segments: VarSpec;
  /** The `angle` variable. */
  readonly angle: VarSpec;
};

/** The shader passes. */
export declare const webgl: WebglBackend;
