// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Levels: Canvas-only: photoshop-style levels — remap input [black, white] to full range with a gamma curve. built as a 256-entry lut applied per channel.
 *
 * @example
 * ```js
 * import { filterToCanvas } from '@aufbau/filters/canvas';
 *
 * await filterToCanvas(canvas, 'levels', { black: 0 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Levels. */
export interface Options extends FilterOptions {
  /** Default `0`, 0 to 1. */
  black?: number;
  /** Default `1`, 0 to 1. */
  white?: number;
  /** Default `1`, 0.1 to 3. */
  gamma?: number;
}

/** The id: `levels`. */
export declare const id: 'levels';

/** The display name: `Levels`. */
export declare const name: 'Levels';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `black` variable. */
  readonly black: VarSpec;
  /** The `white` variable. */
  readonly white: VarSpec;
  /** The `gamma` variable. */
  readonly gamma: VarSpec;
};

/** Filters the pixels of an image in place. */
export declare function canvas (image: ImageData, options?: Options): void;

export default canvas;
