// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Linocut: An svg `<filter>`.
 *
 * @example
 * ```js
 * import linocut from '@aufbau/filters/linocut';
 * import { apply } from '@aufbau/filters';
 *
 * linocut({ levels: 2 });          // the <filter> markup
 * await apply('#photo', 'linocut', { levels: 2 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Linocut. */
export interface Options extends FilterOptions {
  /** Default `2`, 2 to 4. Baked into the markup, never a css custom property. */
  levels?: number;
}

/** The id: `linocut`. */
export declare const id: 'linocut';

/** The display name: `Linocut`. */
export declare const name: 'Linocut';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `levels` variable. */
  readonly levels: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function linocut (options?: Options): string;
