// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Melt: An svg `<filter>`.
 *
 * @example
 * ```js
 * import melt from '@aufbau/filters/melt';
 * import { apply } from '@aufbau/filters';
 *
 * melt({ amount: 15 });          // the <filter> markup
 * await apply('#photo', 'melt', { amount: 15 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Melt. */
export interface Options extends FilterOptions {
  /** `false` holds the effect still. Default `true`. */
  animate?: boolean;
  /** Default `15`, 0 to 60. */
  amount?: number;
  /** Default `"4s"`. Baked into the markup, never a css custom property. */
  speed?: string;
}

/** The id: `melt`. */
export declare const id: 'melt';

/** The display name: `Melt`. */
export declare const name: 'Melt';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `animate` variable. */
  readonly animate: VarSpec;
  /** The `amount` variable. */
  readonly amount: VarSpec;
  /** The `speed` variable. */
  readonly speed: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function melt (options?: Options): string;
