// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Mirror: Webgl-only: reflect one half of the image onto the other. `vertical` mirrors across the horizontal axis instead; `flip` chooses which half is the source. mirror is a geometry reflection, not a filter primitive — svg cannot do it.
 *
 * @example
 * ```js
 * import { filterToWebgl } from '@aufbau/filters/webgl';
 *
 * await filterToWebgl(canvas, 'mirror');
 * ```
 *
 * @module
 */

import type { WebglBackend, FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Mirror. */
export interface Options extends FilterOptions {
  /** `false` holds the effect still. Default `false`. */
  vertical?: boolean;
  /** `false` holds the effect still. Default `false`. */
  flip?: boolean;
}

/** The id: `mirror`. */
export declare const id: 'mirror';

/** The display name: `Mirror`. */
export declare const name: 'Mirror';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `vertical` variable. */
  readonly vertical: VarSpec;
  /** The `flip` variable. */
  readonly flip: VarSpec;
};

/** The shader passes. */
export declare const webgl: WebglBackend;
