// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Night Vision: An svg `<filter>`.
 *
 * @example
 * ```js
 * import nightVision from '@aufbau/filters/night-vision';
 * import { apply } from '@aufbau/filters';
 *
 * nightVision({ noise: 0.5 });          // the <filter> markup
 * await apply('#photo', 'night-vision', { noise: 0.5 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Night Vision. */
export interface Options extends FilterOptions {
  /** `false` holds the effect still. Default `true`. */
  animate?: boolean;
  /** Default `0.5`, 0 to 1. Baked into the markup, never a css custom property. */
  noise?: number;
  /** Default `"0.4s"`. Baked into the markup, never a css custom property. */
  speed?: string;
}

/** The id: `night-vision`. */
export declare const id: 'night-vision';

/** The display name: `Night Vision`. */
export declare const name: 'Night Vision';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `animate` variable. */
  readonly animate: VarSpec;
  /** The `noise` variable. */
  readonly noise: VarSpec;
  /** The `speed` variable. */
  readonly speed: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function nightVision (options?: Options): string;
