// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Noise: Webgl-only: animated film grain via a hash. drive uTime in a rAF loop for live grain; at uTime = 0 it is a fixed grain pattern. the gpu port of the svg `grain` for realtime.
 *
 * @example
 * ```js
 * import { filterToWebgl } from '@aufbau/filters/webgl';
 *
 * await filterToWebgl(canvas, 'noise', { amount: 0.15 });
 * ```
 *
 * @module
 */

import type { WebglBackend, FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Noise. */
export interface Options extends FilterOptions {
  /** Default `0.15`, 0 to 1. */
  amount?: number;
  /** Default `1`, 0.3 to 4. */
  scale?: number;
}

/** The id: `noise`. */
export declare const id: 'noise';

/** The display name: `Noise`. */
export declare const name: 'Noise';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `amount` variable. */
  readonly amount: VarSpec;
  /** The `scale` variable. */
  readonly scale: VarSpec;
};

/** The shader passes. */
export declare const webgl: WebglBackend;

/** The noise shader source, shared with the filters that build on it. */
export declare const NOISE: string;
