// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Pixel Sort: Canvas-only: the classic databending glitch — within each row (or column), spans of pixels brighter than `threshold` are sorted by luminance. impossible with svg/css.
 *
 * @example
 * ```js
 * import { filterToCanvas } from '@aufbau/filters/canvas';
 *
 * await filterToCanvas(canvas, 'pixel-sort', { threshold: 0.5 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Pixel Sort. */
export interface Options extends FilterOptions {
  /** Default `0.5`, 0 to 1. */
  threshold?: number;
  /** `false` holds the effect still. Default `false`. */
  vertical?: boolean;
}

/** The id: `pixel-sort`. */
export declare const id: 'pixel-sort';

/** The display name: `Pixel Sort`. */
export declare const name: 'Pixel Sort';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `threshold` variable. */
  readonly threshold: VarSpec;
  /** The `vertical` variable. */
  readonly vertical: VarSpec;
};

/** Filters the pixels of an image in place. */
export declare function canvas (image: ImageData, options?: Options): void;

export default canvas;
