// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Pixelate: Canvas-only: svg filters cannot downsample, so pixelation lives in the imageData backend. averages each size×size block and paints the block with that colour. no default/svg export — this filter is realised only through filterCanvas().
 *
 * @example
 * ```js
 * import { filterToCanvas } from '@aufbau/filters/canvas';
 *
 * await filterToCanvas(canvas, 'pixelate', { size: 8 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Pixelate. */
export interface Options extends FilterOptions {
  /** Default `8`, 1 to 64 px. */
  size?: number;
}

/** The id: `pixelate`. */
export declare const id: 'pixelate';

/** The display name: `Pixelate`. */
export declare const name: 'Pixelate';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `size` variable. */
  readonly size: VarSpec;
};

/** Filters the pixels of an image in place. */
export declare function canvas (image: ImageData, options?: Options): void;

export default canvas;
