// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Polar Pixelate: Canvas-only: pixelation in polar space around the centre — quantises radius into `rings` and angle into `segments`, then samples the block centre. svg cannot do it.
 *
 * @example
 * ```js
 * import { filterToCanvas } from '@aufbau/filters/canvas';
 *
 * await filterToCanvas(canvas, 'polar-pixelate', { rings: 16 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Polar Pixelate. */
export interface Options extends FilterOptions {
  /** Default `16`, 2 to 80. */
  rings?: number;
  /** Default `60`, 3 to 180. */
  segments?: number;
}

/** The id: `polar-pixelate`. */
export declare const id: 'polar-pixelate';

/** The display name: `Polar Pixelate`. */
export declare const name: 'Polar Pixelate';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `rings` variable. */
  readonly rings: VarSpec;
  /** The `segments` variable. */
  readonly segments: VarSpec;
};

/** Filters the pixels of an image in place. */
export declare function canvas (image: ImageData, options?: Options): void;

export default canvas;
