// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Posterize: An svg `<filter>`.
 *
 * @example
 * ```js
 * import posterize from '@aufbau/filters/posterize';
 * import { apply } from '@aufbau/filters';
 *
 * posterize({ levels: 4 });          // the <filter> markup
 * await apply('#photo', 'posterize', { levels: 4 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Posterize. */
export interface Options extends FilterOptions {
  /** Default `4`, 2 to 12. Baked into the markup, never a css custom property. */
  levels?: number;
}

/** The id: `posterize`. */
export declare const id: 'posterize';

/** The display name: `Posterize`. */
export declare const name: 'Posterize';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `levels` variable. */
  readonly levels: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function posterize (options?: Options): string;
