// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Rainbow: An svg `<filter>`.
 *
 * @example
 * ```js
 * import rainbow from '@aufbau/filters/rainbow';
 * import { apply } from '@aufbau/filters';
 *
 * rainbow({ speed: "3s" });          // the <filter> markup
 * await apply('#photo', 'rainbow', { speed: "3s" });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Rainbow. */
export interface Options extends FilterOptions {
  /** `false` holds the effect still. Default `true`. */
  animate?: boolean;
  /** Default `"3s"`. Baked into the markup, never a css custom property. */
  speed?: string;
}

/** The id: `rainbow`. */
export declare const id: 'rainbow';

/** The display name: `Rainbow`. */
export declare const name: 'Rainbow';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `animate` variable. */
  readonly animate: VarSpec;
  /** The `speed` variable. */
  readonly speed: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function rainbow (options?: Options): string;
