// GENERATED by scripts/types.js — do not edit by hand.

/**
 * RGB Shift: An svg `<filter>`.
 *
 * @example
 * ```js
 * import rgbShift from '@aufbau/filters/rgb-shift';
 * import { apply } from '@aufbau/filters';
 *
 * rgbShift({ amount: 4 });          // the <filter> markup
 * await apply('#photo', 'rgb-shift', { amount: 4 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of RGB Shift. */
export interface Options extends FilterOptions {
  /** Default `4`, 0 to 30. Baked into the markup, never a css custom property. */
  amount?: number;
  /** Default `0`, 0 to 360 deg. Baked into the markup, never a css custom property. */
  angle?: number;
}

/** The id: `rgb-shift`. */
export declare const id: 'rgb-shift';

/** The display name: `RGB Shift`. */
export declare const name: 'RGB Shift';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `amount` variable. */
  readonly amount: VarSpec;
  /** The `angle` variable. */
  readonly angle: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function rgbShift (options?: Options): string;
