// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Saturate: An svg `<filter>`.
 *
 * @example
 * ```js
 * import saturate from '@aufbau/filters/saturate';
 * import { apply } from '@aufbau/filters';
 *
 * saturate({ amount: 1.5 });          // the <filter> markup
 * await apply('#photo', 'saturate', { amount: 1.5 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Saturate. */
export interface Options extends FilterOptions {
  /** Default `1.5`, 0 to 4. */
  amount?: number;
}

/** The id: `saturate`. */
export declare const id: 'saturate';

/** The display name: `Saturate`. */
export declare const name: 'Saturate';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `amount` variable. */
  readonly amount: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function saturate (options?: Options): string;

/** The native css filter function for a set of options. */
export declare function css (options?: Options): string;
