// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Scanlines: An svg `<filter>`.
 *
 * @example
 * ```js
 * import scanlines from '@aufbau/filters/scanlines';
 * import { apply } from '@aufbau/filters';
 *
 * scanlines({ gap: 4 });          // the <filter> markup
 * await apply('#photo', 'scanlines', { gap: 4 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Scanlines. */
export interface Options extends FilterOptions {
  /** `false` holds the effect still. Default `false`. */
  animate?: boolean;
  /** Default `4`, 2 to 20. Baked into the markup, never a css custom property. */
  gap?: number;
  /** Default `1`, 0.5 to 6. Baked into the markup, never a css custom property. */
  thickness?: number;
  /** Default `0.35`, 0 to 1. Baked into the markup, never a css custom property. */
  opacity?: number;
  /** Default `"4s"`. Baked into the markup, never a css custom property. */
  speed?: string;
}

/** The id: `scanlines`. */
export declare const id: 'scanlines';

/** The display name: `Scanlines`. */
export declare const name: 'Scanlines';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `animate` variable. */
  readonly animate: VarSpec;
  /** The `gap` variable. */
  readonly gap: VarSpec;
  /** The `thickness` variable. */
  readonly thickness: VarSpec;
  /** The `opacity` variable. */
  readonly opacity: VarSpec;
  /** The `speed` variable. */
  readonly speed: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function scanlines (options?: Options): string;
