// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Sepia: An svg `<filter>`.
 *
 * @example
 * ```js
 * import sepia from '@aufbau/filters/sepia';
 * import { apply } from '@aufbau/filters';
 *
 * sepia({ amount: 1 });          // the <filter> markup
 * await apply('#photo', 'sepia', { amount: 1 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Sepia. */
export interface Options extends FilterOptions {
  /** Default `1`, 0 to 1. */
  amount?: number;
}

/** The id: `sepia`. */
export declare const id: 'sepia';

/** The display name: `Sepia`. */
export declare const name: 'Sepia';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `amount` variable. */
  readonly amount: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function sepia (options?: Options): string;

/** The native css filter function for a set of options. */
export declare function css (options?: Options): string;
