// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Shake: An svg `<filter>`.
 *
 * @example
 * ```js
 * import shake from '@aufbau/filters/shake';
 * import { apply } from '@aufbau/filters';
 *
 * shake({ amount: 5 });          // the <filter> markup
 * await apply('#photo', 'shake', { amount: 5 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Shake. */
export interface Options extends FilterOptions {
  /** `false` holds the effect still. Default `true`. */
  animate?: boolean;
  /** Default `5`, 0 to 40. Baked into the markup, never a css custom property. */
  amount?: number;
  /** Default `"0.4s"`. Baked into the markup, never a css custom property. */
  speed?: string;
}

/** The id: `shake`. */
export declare const id: 'shake';

/** The display name: `Shake`. */
export declare const name: 'Shake';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `animate` variable. */
  readonly animate: VarSpec;
  /** The `amount` variable. */
  readonly amount: VarSpec;
  /** The `speed` variable. */
  readonly speed: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function shake (options?: Options): string;
