// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Sharpen: An svg `<filter>`.
 *
 * @example
 * ```js
 * import sharpen from '@aufbau/filters/sharpen';
 * import { apply } from '@aufbau/filters';
 *
 * sharpen({ strength: 1 });          // the <filter> markup
 * await apply('#photo', 'sharpen', { strength: 1 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Sharpen. */
export interface Options extends FilterOptions {
  /** Default `1`, 0 to 3. Baked into the markup, never a css custom property. */
  strength?: number;
}

/** The id: `sharpen`. */
export declare const id: 'sharpen';

/** The display name: `Sharpen`. */
export declare const name: 'Sharpen';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `strength` variable. */
  readonly strength: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function sharpen (options?: Options): string;
