// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Slices: An svg `<filter>`.
 *
 * @example
 * ```js
 * import slices from '@aufbau/filters/slices';
 * import { apply } from '@aufbau/filters';
 *
 * slices({ amount: 20 });          // the <filter> markup
 * await apply('#photo', 'slices', { amount: 20 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Slices. */
export interface Options extends FilterOptions {
  /** `false` holds the effect still. Default `false`. */
  animate?: boolean;
  /** Default `20`, 0 to 80. */
  amount?: number;
  /** Default `8`, 2 to 40. Baked into the markup, never a css custom property. */
  count?: number;
  /** Default `"0.5s"`. Baked into the markup, never a css custom property. */
  speed?: string;
}

/** The id: `slices`. */
export declare const id: 'slices';

/** The display name: `Slices`. */
export declare const name: 'Slices';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `animate` variable. */
  readonly animate: VarSpec;
  /** The `amount` variable. */
  readonly amount: VarSpec;
  /** The `count` variable. */
  readonly count: VarSpec;
  /** The `speed` variable. */
  readonly speed: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function slices (options?: Options): string;
