// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Smear: An svg `<filter>`.
 *
 * @example
 * ```js
 * import smear from '@aufbau/filters/smear';
 * import { apply } from '@aufbau/filters';
 *
 * smear({ x: 8 });          // the <filter> markup
 * await apply('#photo', 'smear', { x: 8 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Smear. */
export interface Options extends FilterOptions {
  /** Default `8`, 0 to 40 px. */
  x?: number;
  /** Default `0`, 0 to 40 px. */
  y?: number;
}

/** The id: `smear`. */
export declare const id: 'smear';

/** The display name: `Smear`. */
export declare const name: 'Smear';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `x` variable. */
  readonly x: VarSpec;
  /** The `y` variable. */
  readonly y: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function smear (options?: Options): string;
