// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Solarize: An svg `<filter>`.
 *
 * @example
 * ```js
 * import solarize from '@aufbau/filters/solarize';
 * import { apply } from '@aufbau/filters';
 *
 * solarize({ intensity: 1 });          // the <filter> markup
 * await apply('#photo', 'solarize', { intensity: 1 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Solarize. */
export interface Options extends FilterOptions {
  /** Default `1`, 0 to 1. Baked into the markup, never a css custom property. */
  intensity?: number;
}

/** The id: `solarize`. */
export declare const id: 'solarize';

/** The display name: `Solarize`. */
export declare const name: 'Solarize';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `intensity` variable. */
  readonly intensity: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function solarize (options?: Options): string;
