// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Thermal: An svg `<filter>`.
 *
 * @example
 * ```js
 * import thermal from '@aufbau/filters/thermal';
 * import { apply } from '@aufbau/filters';
 *
 * thermal();          // the <filter> markup
 * await apply('#photo', 'thermal');
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Thermal. */
export interface Options extends FilterOptions {

}

/** The id: `thermal`. */
export declare const id: 'thermal';

/** The display name: `Thermal`. */
export declare const name: 'Thermal';

/** The variables, what each takes and its default. */
export declare const vars: {

};

/** The `<filter>` markup for a set of options. */
export default function thermal (options?: Options): string;
