// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Threshold: Canvas-only: hard 1-bit cut of the luminance at `level`. (svg can approximate this with a discrete transfer, but it lives here as a plain imageData example.)
 *
 * @example
 * ```js
 * import { filterToCanvas } from '@aufbau/filters/canvas';
 *
 * await filterToCanvas(canvas, 'threshold', { level: 0.5 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Threshold. */
export interface Options extends FilterOptions {
  /** Default `0.5`, 0 to 1. */
  level?: number;
}

/** The id: `threshold`. */
export declare const id: 'threshold';

/** The display name: `Threshold`. */
export declare const name: 'Threshold';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `level` variable. */
  readonly level: VarSpec;
};

/** Filters the pixels of an image in place. */
export declare function canvas (image: ImageData, options?: Options): void;

export default canvas;
