// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Tilt Shift: An svg `<filter>`.
 *
 * @example
 * ```js
 * import tiltShift from '@aufbau/filters/tilt-shift';
 * import { apply } from '@aufbau/filters';
 *
 * tiltShift({ amount: 6 });          // the <filter> markup
 * await apply('#photo', 'tilt-shift', { amount: 6 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Tilt Shift. */
export interface Options extends FilterOptions {
  /** Default `6`, 0 to 20 px. */
  amount?: number;
  /** Default `0.3`, 0.05 to 0.9. Baked into the markup, never a css custom property. */
  band?: number;
}

/** The id: `tilt-shift`. */
export declare const id: 'tilt-shift';

/** The display name: `Tilt Shift`. */
export declare const name: 'Tilt Shift';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `amount` variable. */
  readonly amount: VarSpec;
  /** The `band` variable. */
  readonly band: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function tiltShift (options?: Options): string;
