// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Vignette: An svg `<filter>`.
 *
 * @example
 * ```js
 * import vignette from '@aufbau/filters/vignette';
 * import { apply } from '@aufbau/filters';
 *
 * vignette({ amount: 0.6 });          // the <filter> markup
 * await apply('#photo', 'vignette', { amount: 0.6 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Vignette. */
export interface Options extends FilterOptions {
  /** Default `0.6`, 0 to 1. Baked into the markup, never a css custom property. */
  amount?: number;
  /** Default `0.5`, 0 to 1. Baked into the markup, never a css custom property. */
  size?: number;
}

/** The id: `vignette`. */
export declare const id: 'vignette';

/** The display name: `Vignette`. */
export declare const name: 'Vignette';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `amount` variable. */
  readonly amount: VarSpec;
  /** The `size` variable. */
  readonly size: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function vignette (options?: Options): string;
