// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Wave: An svg `<filter>`.
 *
 * @example
 * ```js
 * import wave from '@aufbau/filters/wave';
 * import { apply } from '@aufbau/filters';
 *
 * wave({ frequency: 0.02 });          // the <filter> markup
 * await apply('#photo', 'wave', { frequency: 0.02 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Wave. */
export interface Options extends FilterOptions {
  /** Default `0.02`, 0 to 0.2. */
  frequency?: number;
  /** Default `2`, 1 to 5. */
  octaves?: number;
  /** Default `20`, 0 to 100. */
  scale?: number;
}

/** The id: `wave`. */
export declare const id: 'wave';

/** The display name: `Wave`. */
export declare const name: 'Wave';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `frequency` variable. */
  readonly frequency: VarSpec;
  /** The `octaves` variable. */
  readonly octaves: VarSpec;
  /** The `scale` variable. */
  readonly scale: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function wave (options?: Options): string;
