// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Wobble: An svg `<filter>`.
 *
 * @example
 * ```js
 * import wobble from '@aufbau/filters/wobble';
 * import { apply } from '@aufbau/filters';
 *
 * wobble({ amount: 8 });          // the <filter> markup
 * await apply('#photo', 'wobble', { amount: 8 });
 * ```
 *
 * @module
 */

import type { FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Wobble. */
export interface Options extends FilterOptions {
  /** `false` holds the effect still. Default `true`. */
  animate?: boolean;
  /** Default `8`, 0 to 40. */
  amount?: number;
  /** Default `0.02`, 0.005 to 0.1. */
  frequency?: number;
  /** Default `"3s"`. Baked into the markup, never a css custom property. */
  speed?: string;
}

/** The id: `wobble`. */
export declare const id: 'wobble';

/** The display name: `Wobble`. */
export declare const name: 'Wobble';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `animate` variable. */
  readonly animate: VarSpec;
  /** The `amount` variable. */
  readonly amount: VarSpec;
  /** The `frequency` variable. */
  readonly frequency: VarSpec;
  /** The `speed` variable. */
  readonly speed: VarSpec;
};

/** The `<filter>` markup for a set of options. */
export default function wobble (options?: Options): string;
