// GENERATED by scripts/types.js — do not edit by hand.

/**
 * Zoom Blur: Webgl-only: radial/zoom blur — samples along the line toward the centre. this is the real effect our svg `barrel-blur` only approximated with an edge falloff.
 *
 * @example
 * ```js
 * import { filterToWebgl } from '@aufbau/filters/webgl';
 *
 * await filterToWebgl(canvas, 'zoom-blur', { strength: 0.2 });
 * ```
 *
 * @module
 */

import type { WebglBackend, FilterOptions, VarSpec } from '../types.d.ts';

/** The options of Zoom Blur. */
export interface Options extends FilterOptions {
  /** Default `0.2`, 0 to 1. */
  strength?: number;
}

/** The id: `zoom-blur`. */
export declare const id: 'zoom-blur';

/** The display name: `Zoom Blur`. */
export declare const name: 'Zoom Blur';

/** The variables, what each takes and its default. */
export declare const vars: {
  /** The `strength` variable. */
  readonly strength: VarSpec;
};

/** The shader passes. */
export declare const webgl: WebglBackend;
